about:
  home: www.walberla.net
  license: GPLv3
  summary: High Performance, Multi-physics Simulation Framework

package:
  name: walberla
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
  build:
  - {{ compiler('cxx') }}
  - python
  - git
  - boost
  - cmake [linux]
  - cmake >=3.7.0 [win]
  - make
  - mpich2 [linux]
  run:
  - python
  - boost
  - numpy
  - mpich2 [linux]
source:
  path: ../../..

test:
  imports:
    - waLBerla