about:
  home: www.walberla.net
  license: GPLv3
  summary: High Performance, Multi-physics Simulation Framework

package:
  name: walberla-lbm
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
  build:
  - {{ compiler('cxx') }}
  - git
  - cmake
  - make
  host:
  - python
  - boost
  - mpich2 [linux]
  - openmesh
  run:
  - python >=3.6
  - boost
  - numpy
  - mpich2 [linux]
  - openmesh
source:
  path: ../../..
