about:
  home: www.walberla.net
  license: GPLv3
package:
  name: walberla-lbm
  version: {{ GIT_DESCRIBE_TAG }}
build:
  number: {{ GIT_DESCRIBE_NUMBER }}


requirements:
  build:
  - python
  - git
  - boost
  - cmake
  - gcc [linux]
  - mpich2 [linux]
  run:
  - python >=3.6
  - boost
  - numpy
  - mpich2 [linux]
source:
  git_rev: master
  git_url: https://i10git.cs.fau.de/walberla/walberla.git
